name: azure setup
on: 
  push:
    paths:
    - 'azure/**'
    - '.github/**'
jobs:
  check-azure:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az webapp list --query "[?state=='Running']"

    - name: last step
      run: echo "last step"
    
