name: Repository Dispatch
on:
  repository_dispatch:
    types: update-on-release
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github }}
      - run: echo ${{ github }} > version.txt
      - name: Check for version file
        run: cat version.txt

  
