name: Repository Dispatch
on:
  repository_dispatch:
    types: update-on-release
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.ref }} , ${{ fromJson(github.event.client_payload.github) }}


  
