name: Repository Dispatch
on:
  repository_dispatch:
    types: update-on-release
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      #- run: echo ${{ github.event.client_payload.ref }} 
      #- run: echo ${{ fromJson(github.event.client_payload.github) }} 
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.client_payload.release }} |
             sed s/$/.0/ | 
             sed s/v// > version.txt
      - name: "Set version string"
        run: echo version.txt
      - run: echo ::set-env name=VERSION_STRING::$(cat version.txt)
      - name: check version
        run: echo $env.VERSION_STRING

             
               
        


  
