name: Repository Dispatch
on:
  repository_dispatch:
    types: update-on-release
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      #- run: echo ${{ github.event.client_payload.ref }} 
      #- run: echo ${{ fromJson(github.event.client_payload.github) }} 
      - run: echo ${{ github.event.client_payload.release }} |
             sed s/$/.0/ | 
             sed s/v//
               
        


  
